name: Azure ML Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}
  LOCATION: ${{ secrets.LOCATION }}
  STORAGE_NAME: ${{ secrets.STORAGE_NAME}}

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install azure-ai-ml azure-identity
    
    - name: ML resource create
      run: python src/resourcecreate.py
    
    - name: Wait 7 minutes
      run: sleep 0 

    - name: Data preprocess and clustering
      run: python src/runpipline.py

    - name: Wait 7 minutes
      run: sleep 60 

    - name: Run Delete resource
      run: python src/resorceclean.py
